config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope module: :web do
    root 'welcome#index'

    get '/uslugi', to: 'pages#servise'
    get '/about_me', to: 'pages#about_me'
    resources :categories, only: [:show]
    resources :galleries, only: [:show]
    resources :reviews, only: [:index]
    resources :pages, only: [:show]

    namespace :admin do
      root 'welcome#index'
      resource :session, only: [:new, :create, :destroy]
      resources :pictures
      resources :categories
      resources :calendars, only: [:index]
      resources :galleries, only: [:index, :new, :edit, :destroy]
      resources :reviews, only: [:index, :new, :create, :update, :edit, :destroy]
      resources :pages, only: [:index, :new, :create, :update, :edit, :destroy]
    end
  end

  namespace :api do
    namespace :admin do
      resources :pictures, only: [:create, :update, :destroy] do
        post 'save_favorite'
        post 'delete_favorite'
      end
      resources :calendars, only: [:create, :destroy]
      resources :galleries, only: [:create, :update, :destroy]
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :gallery
  belongs_to :picture
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  validates :date, uniqueness: true, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  has_and_belongs_to_many :galleries

  friendly_id :title, use: :slugged
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Backend::Refile
  include Ckeditor::Orm::ActiveRecord::AssetBase
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  attachment :data, extension: attachment_file_types

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  attachment :data, extension: image_file_types

  def url_content
    url
  end

  def url_thumb
    url(:fill, 118, 100)
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  extend FriendlyId
  # validates :slug, slug: true, presence: true, uniqueness: true
  
  has_many :pictures, through: :attachments
  has_many :attachments, dependent: :destroy
  has_and_belongs_to_many :categories

  attachment :cover, type: :image
  friendly_id :title, use: :slugged

  accepts_nested_attributes_for :pictures, allow_destroy: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :galleries, through: :attachments
  has_many :attachments, dependent: :destroy

  extend Enumerize

  attachment :image, type: :image
  enumerize :publish_state, in: [:active, :deleted], default: :active

  accepts_nested_attributes_for :attachments
end

app/models/review.rb
class Review < ActiveRecord::Base
  attachment :image, type: :image
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :email, uniqueness: true, presence: true, email: true
end

app/controllers/api/admin/galleries_controller.rb
class Api::Admin::GalleriesController < Api::Admin::ApplicationController
  def create
    gallery = Gallery.new(gallery_params)
    cover_id = params[:cover_id]

    puts(cover_id)

    if gallery.save
      # cover_picture = Picture.find_by()
      render json: gallery, status: :created
    else
      render json: { errors: gallery.errors }, status: :bad_request
    end
  end

  def update
    gallery = Gallery.friendly.find(params[:id])
    gallery.assign_attributes(gallery_params)

    if gallery.save
      render json: gallery, status: :created
    else
      render json: { errors: gallery.errors }, status: :bad_request
    end
  end

  def destroy
    gallery = Gallery.friendly.find(params[:id])
    gallery.destroy

    respond_with gallery
  end

  private

  def gallery_params
    params.require(:gallery).permit(
        :title, :slug, :cover, category_ids:[],
        pictures_attributes: [:id, :title, :image, :filename, :size, :_destroy,
        :attachments_attributes => [:id, :gallery_id, :picture_id, :order]]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Concerns::MenuConcern

  helper_method :categories_menu
end

app/controllers/concerns/flash_helper.rb
module Concerns
  module FlashHelper
    def f(key, options = {})
      scope = [:flash]
      type = options[:type] || key

      default_scope = scope.dup
      default_scope << 'base' << params[:action]

      default_msg = I18n.t(key, scope: default_scope)

      current_scope = scope.dup
      current_scope << params[:controller].split('/')
      current_scope << params[:action]

      msg = I18n.t(key, scope: current_scope, default: default_msg)

      if options[:now]
        flash.now[type] = msg
      else
        flash[type] = msg
      end
    end
  end
end

app/controllers/concerns/menu_concern.rb
module Concerns::MenuConcern
  def categories_menu
    Category.all
  end
end

app/controllers/concerns/serialize.rb
module Concerns::Serialize
  def serialize(resource, options = {})
    return unless resource
    ActiveModel::SerializableResource.new(resource, options).serializable_hash
  end
end

app/controllers/web/admin/galleries_controller.rb
class Web::Admin::GalleriesController < Web::Admin::ApplicationController
  def index
    @q = Gallery.ransack(params[:q])
    @galleries = @q.result.order(created_at: :desc).page(params[:page])
  end

  def new
    @gallery = Gallery.new
    @categories = Category.all
    @categories_serialized = serialize(@categories)
  end

  def edit
    @gallery = Gallery.friendly.find(params[:id])
    @gallery_serialized = serialize(@gallery)
    @pictures_serialized = serialize(@gallery.pictures)
    @attachments_serialized = serialize(@gallery.attachments)
    @categories = Category.all
    @categories_serialized = serialize(@categories)
  end

  def destroy
    gallery = Gallery.friendly.find(params[:id])
    gallery.destroy
    f :success
    redirect_to action: :index
  end

end

app/controllers/web/galleries_controller.rb
class Web::GalleriesController < Web::ApplicationController
  def show
    @gallery = Gallery.friendly.find(params[:id])
    @categories = @gallery.categories
    @pictures = @gallery.pictures
    @pictures_serialized = serialize(@pictures)
  end
end

app/controllers/web/pages_controller.rb
class Web::PagesController < Web::ApplicationController
  def show
    @page = Page.friendly.find(params[:id])
  end

  def servise
    @servise = Page.find_by(slug: 'uslugi')
    @events = Calendar.all
    @events_serialized = serialize(@events)
  end

  def about_me
    @about_me = Page.find_by(slug: 'kontakty')
  end
end

app/controllers/web/reviews_controller.rb
class Web::ReviewsController < Web::ApplicationController
  def index
    @reviews = Review.all
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
    @favorites = Picture.where(favorite: true)
    @favorites_serialized = serialize(@favorites)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/model_helper.rb
module ModelHelper
  def han(model, attribute)
    model.to_s.classify.constantize.human_attribute_name(attribute)
  end
end

app/helpers/react_helper.rb
module ReactHelper
  def env_javascript_include_tag(args = {})
    send_tag_method(:javascript_include_tag, args)
  end

  def env_stylesheet_link_tag(args = {})
    send_tag_method(:stylesheet_link_tag, args)
  end

  def use_hot_reloading?
    ENV['REACT_ON_RAILS_ENV'] == 'HOT'
  end

  private

  def send_tag_method(tag_method_name, args)
    puts use_hot_reloading?
    asset_type = use_hot_reloading? ? :hot : :static
    assets = Array(args[asset_type])
    options = args.delete_if { |key, _value| %i(hot static).include?(key) }
    send(tag_method_name, *assets, options) unless assets.empty?
  end
end

app/views/web/admin/galleries/edit.html.haml
.row
  .col-lg-12
    .clearfix
      %h1.pull-left
        = Gallery.model_name.human(count: 2)
        %small= t(".sub_title")
.row
  .col-lg-12
    .main-box.no-header.clearfix
      .main-box-body.clearfix
        = react_component('GalleryForm', gallery: @gallery_serialized,
                                         categories: @categories_serialized,
                                         attachments: @attachments_serialized,
                                         actionUrl: api_admin_gallery_path(@gallery.id),
                                         existPictures: @pictures_serialized,
                                         submitTitle: 'Изменить галерею')

app/views/web/admin/galleries/index.html.haml
.row
  .col-lg-12
    .clearfix
      %h1.pull-left= Gallery.model_name.human(count: 2)
      .pull-right.top-page-ui
        = link_to new_admin_gallery_path, class: "btn btn-primary pull-right" do
          %i.fa.fa-plus-circle.fa-lg
          = t('.add')

.row
  .col-lg-12
    .main-box.no-header.clearfix
      .main-box-body.clearfix
        .table-responsive
          %table.table
            %thead
              %tr
                %th= han(Gallery, :title)
                %th
            %tbody
              - @galleries.each do |gallery|
                %tr
                  %td= gallery.title
                  %td{style: "width: 15%"}
                    = link_to edit_admin_gallery_path(gallery), class: "table-link" do
                      %span.fa-stack
                        %i.fa.fa-square.fa-stack-2x
                        %i.fa.fa-pencil.fa-stack-1x.fa-inverse
                    = link_to admin_gallery_path(gallery), method: :delete, data: {confirm: t('confirm')}, class: "table-link danger" do
                      %span.fa-stack
                        %i.fa.fa-square.fa-stack-2x
                        %i.fa.fa-trash-o.fa-stack-1x.fa-inverse

app/views/web/admin/galleries/new.html.haml
.row
  .col-lg-12
    .clearfix
      %h1.pull-left
        = Gallery.model_name.human(count: 2)
        %small= t(".sub_title")
.row
  .col-lg-12
    .main-box.no-header.clearfix
      .main-box-body.clearfix
        = react_component('GalleryForm', categories: @categories_serialized, actionUrl: api_admin_galleries_path, submitTitle: 'Дабавить галерею')

app/views/web/galleries/show.html.haml
.intro
  .intro__content
    %h1.intro__title= @gallery.title
    %h2.intro__sub-title
      Галереи:
      - @categories.each do |category|
        = link_to category.title, category, class: 'intro__link'

= react_component('Gallery', pictures: @pictures_serialized)