config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope module: :web do
    root 'welcome#index'

    get '/uslugi', to: 'pages#servise'
    get '/about_me', to: 'pages#about_me'
    resources :categories, only: [:show]
    resources :galleries, only: [:show]
    resources :reviews, only: [:index]
    resources :pages, only: [:show]

    namespace :admin do
      root 'welcome#index'
      resource :session, only: [:new, :create, :destroy]
      resources :pictures
      resources :categories
      resources :calendars, only: [:index]
      resources :galleries, only: [:index, :new, :edit, :destroy]
      resources :reviews, only: [:index, :new, :create, :update, :edit, :destroy]
      resources :pages, only: [:index, :new, :create, :update, :edit, :destroy]
    end
  end

  namespace :api do
    namespace :admin do
      resources :pictures, only: [:create, :update, :destroy] do
        post 'save_favorite'
        post 'delete_favorite'
      end
      resources :calendars, only: [:create, :destroy]
      resources :galleries, only: [:create, :update, :destroy]
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :gallery
  belongs_to :picture
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  validates :date, uniqueness: true, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  has_and_belongs_to_many :galleries

  friendly_id :title, use: :slugged
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Backend::Refile
  include Ckeditor::Orm::ActiveRecord::AssetBase
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  attachment :data, extension: attachment_file_types

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  attachment :data, extension: image_file_types

  def url_content
    url
  end

  def url_thumb
    url(:fill, 118, 100)
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  extend FriendlyId
  # validates :slug, slug: true, presence: true, uniqueness: true
  
  has_many :pictures, through: :attachments
  has_many :attachments, dependent: :destroy
  has_and_belongs_to_many :categories

  attachment :cover, type: :image
  friendly_id :title, use: :slugged

  accepts_nested_attributes_for :pictures, allow_destroy: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, use: :slugged
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :galleries, through: :attachments
  has_many :attachments, dependent: :destroy

  extend Enumerize

  attachment :image, type: :image
  enumerize :publish_state, in: [:active, :deleted], default: :active

  accepts_nested_attributes_for :attachments
end

app/models/review.rb
class Review < ActiveRecord::Base
  attachment :image, type: :image
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :email, uniqueness: true, presence: true, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Concerns::MenuConcern

  helper_method :categories_menu
end

app/controllers/concerns/flash_helper.rb
module Concerns
  module FlashHelper
    def f(key, options = {})
      scope = [:flash]
      type = options[:type] || key

      default_scope = scope.dup
      default_scope << 'base' << params[:action]

      default_msg = I18n.t(key, scope: default_scope)

      current_scope = scope.dup
      current_scope << params[:controller].split('/')
      current_scope << params[:action]

      msg = I18n.t(key, scope: current_scope, default: default_msg)

      if options[:now]
        flash.now[type] = msg
      else
        flash[type] = msg
      end
    end
  end
end

app/controllers/concerns/menu_concern.rb
module Concerns::MenuConcern
  def categories_menu
    Category.all
  end
end

app/controllers/concerns/serialize.rb
module Concerns::Serialize
  def serialize(resource, options = {})
    return unless resource
    ActiveModel::SerializableResource.new(resource, options).serializable_hash
  end
end

app/controllers/web/pages_controller.rb
class Web::PagesController < Web::ApplicationController
  def show
    @page = Page.friendly.find(params[:id])
  end

  def servise
    @servise = Page.find_by(slug: 'uslugi')
    @events = Calendar.all
    @events_serialized = serialize(@events)
  end

  def about_me
    @about_me = Page.find_by(slug: 'kontakty')
  end
end

app/controllers/web/reviews_controller.rb
class Web::ReviewsController < Web::ApplicationController
  def index
    @reviews = Review.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/model_helper.rb
module ModelHelper
  def han(model, attribute)
    model.to_s.classify.constantize.human_attribute_name(attribute)
  end
end

app/helpers/react_helper.rb
module ReactHelper
  def env_javascript_include_tag(args = {})
    send_tag_method(:javascript_include_tag, args)
  end

  def env_stylesheet_link_tag(args = {})
    send_tag_method(:stylesheet_link_tag, args)
  end

  def use_hot_reloading?
    ENV['REACT_ON_RAILS_ENV'] == 'HOT'
  end

  private

  def send_tag_method(tag_method_name, args)
    puts use_hot_reloading?
    asset_type = use_hot_reloading? ? :hot : :static
    assets = Array(args[asset_type])
    options = args.delete_if { |key, _value| %i(hot static).include?(key) }
    send(tag_method_name, *assets, options) unless assets.empty?
  end
end

app/views/layouts/web/admin/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    - if content_for? :title
      = yield :title
    - else
      %title!= 'Happsyphoto admin'
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic&subset=latin,cyrillic-ext", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,300italic,300,400italic,600,600italic,700,700italic&subset=latin,cyrillic-ext", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    = env_stylesheet_link_tag(static: 'admin/application_static', hot: ['http://localhost:9090/admin-bundle.css', 'admin/application_non_webpack'], media: 'all')

    = include_gon
    = javascript_include_tag 'admin/application', 'data-turbolinks-track' => true
    = env_javascript_include_tag(hot: ['http://localhost:9090/vendor-bundle.js', 'http://localhost:9090/admin-bundle.js'])
    = env_javascript_include_tag(static: 'application_admin_static', hot: 'application_admin_non_webpack')
    = csrf_meta_tags
    :javascript
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale = "#{I18n.default_locale}";
    = favicon_link_tag 'favicon.ico'
  %body
    = render 'shared/admin/header'
    #page-wrapper.container
      .row
        #nav-col
          = render 'shared/admin/aside'
        #content-wrapper
          .row
            .col-lg-12
              = yield

app/views/layouts/web/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    -#%meta{name: "viewport", content: "width=device-width, initial-scale=1, user-scalable=no"}/
    - if content_for? :title
      = yield :title
    - else
      %title!= 'Happsyphoto'
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic&subset=latin,cyrillic-ext", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,300italic,300,400italic,600,600italic,700,700italic&subset=latin,cyrillic-ext", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
    = env_stylesheet_link_tag(static: 'web/application_static', hot: ['http://0.0.0.0:9090/web-bundle.css', 'web/application_non_webpack'], media: 'all')

    = include_gon
    = javascript_include_tag 'web/application', 'data-turbolinks-track' => true
    = env_javascript_include_tag(hot: ['http://0.0.0.0:9090/vendor-bundle.js', 'http://0.0.0.0:9090/web-bundle.js'])
    = env_javascript_include_tag(static: 'application_static', hot: 'application_non_webpack')
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  %body
    = render "shared/counter"
    .l-wrap
      = render "shared/header"
      .l-basic
        .l-content
          = yield
    = render "shared/footer"
    = react_component('ScrollToTop')

app/views/shared/_counter.html.haml
- if Rails.env.production?
  / Yandex.Metrika counter
  :javascript
    (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
    try {
    w.yaCounter21293449 = new Ya.Metrika({
    id:21293449,
    clickmap:true,
    trackLinks:true,
    accurateTrackBounce:true
    });
    } catch(e) { }
    });
    
    var n = d.getElementsByTagName("script")[0],
    s = d.createElement("script"),
    f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://mc.yandex.ru/metrika/watch.js";
    
    if (w.opera == "[object Opera]") {
    d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
  %noscript
    %div
      %img{:alt => "", :src => "https://mc.yandex.ru/watch/21293449", :style => "position:absolute; left:-9999px;"}/
  / /Yandex.Metrika counter

app/views/shared/_footer.html.haml
%footer.footer.js-footer
  .footer__social
    %span.footer__social-icon
      = link_to 'https://vk.com/happsy', class: 'fa fa-vk footer__social-link', target: '_blank' do
        %span.footer__social-icon-title vk.com/happsy
    %span.footer__social-icon
      = link_to 'https://www.instagram.com/galichnikov_dmitry/', class: 'fa fa-instagram footer__social-link', target: '_blank' do
        %span.footer__social-icon-title instagram.com/galichnikov_dmitry

app/views/shared/_header.html.haml
%header.header.js-header
  .header__inner
    .header__logo
      = link_to root_path, class: 'logo' do
        = image_tag 'logo.png', class: 'header__img'
    .header__nav-menu
      = render 'shared/nav_menu'

app/views/shared/_nav_menu.html.haml
%nav.nav-menu
  %ul.nav-menu__list
    %li.nav-menu__item
      = link_to t('.main'), root_path, class: 'nav-menu__item-link'
    %li.nav-menu__item
      .nav-menu__item-drop
        %span.nav-menu__item-drop-title
          = t('.category')
        %div.nav-menu__submenu
          - categories_menu.each do |category|
            = link_to category.title, category_path(category), class: 'nav-menu__item-sublink'
    %li.nav-menu__item
      = link_to t('.contacts'), about_me_path, class: 'nav-menu__item-link'
    %li.nav-menu__item
      = link_to t('.reviews'), reviews_path, class: 'nav-menu__item-link'
    %li.nav-menu__item
      = link_to t('.servise'), uslugi_path, class: 'nav-menu__item-link'

app/views/web/admin/pages/_form.html.haml
= simple_form_for [:admin, @page] do |f|
  = f.input :title
  = f.input :body, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } }
  = f.submit t(action_name), class: 'btn btn-primary'

app/views/web/admin/pages/edit.html.haml
.row
  .col-lg-12
    .clearfix
      %h1.pull-left
        = Page.model_name.human(count: 2)
        %small= t(".sub_title")
.row
  .col-lg-12
    .main-box.no-header.clearfix
      .main-box-body.clearfix
        = render "form"

app/views/web/admin/pages/index.html.haml
.row
  .col-lg-12
    .clearfix
      %h1.pull-left= Page.model_name.human(count: 2)
      .pull-right.top-page-ui
        = link_to new_admin_page_path, class: "btn btn-primary pull-right" do
          %i.fa.fa-plus-circle.fa-lg
          = t('.add')

.row
  .col-lg-12
    .main-box.no-header.clearfix
      .main-box-body.clearfix
        .table-responsive
          %table.table
            %thead
              %tr
                %th= han(Page, :title)
                %th
            %tbody
              - @pages.each do |page|
                %tr
                  %td= page.title
                  %td{style: "width: 15%"}
                    = link_to edit_admin_page_path(page), class: "table-link" do
                      %span.fa-stack
                        %i.fa.fa-square.fa-stack-2x
                        %i.fa.fa-pencil.fa-stack-1x.fa-inverse
                    = link_to admin_page_path(page), method: :delete, data: {confirm: t('confirm')}, class: "table-link danger" do
                      %span.fa-stack
                        %i.fa.fa-square.fa-stack-2x
                        %i.fa.fa-trash-o.fa-stack-1x.fa-inverse

app/views/web/admin/pages/new.html.haml
.row
  .col-lg-12
    .clearfix
      %h1.pull-left
        = Category.model_name.human(count: 2)
        %small= t(".sub_title")
.row
  .col-lg-12
    .main-box.no-header.clearfix
      .main-box-body.clearfix
        = render "form"

app/views/web/pages/about_me.html.haml
.intro
  .intro__content
    %h1.intro__title Контакты

.l-center.l-center_narrow
  = @about_me.body.html_safe

app/views/web/pages/servise.html.haml
.intro
  .intro__content
    %h1.intro__title Услуги
.l-center
  = @servise.body.html_safe
.l-center.l-center_narrow
  %h2.headline Календарь
  = react_component('CalendarEvents', events: @events_serialized)